title: Greg Edwards # your name (or website title) here
logo: "/images/P1030181.JPG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Transportation and Spatial Planner @ Beca 
  <br><br>
  I believe maps, data science, and urban analytics can help us make better, more-informed transport and urban planning decisions.
  <br><br>
  <a href="https://www.linkedin.com/in/gregedwards1/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
